DROP TABLE IF EXISTS TRANSACTION;
  
CREATE TABLE TRANSACTION (
  reference VARCHAR(16) PRIMARY KEY,
  iban VARCHAR(250) NOT NULL,
  date TIMESTAMP NOT NULL,
  amount FLOAT NOT NULL,
  fee FLOAT NOT NULL,
  description VARCHAR(250) DEFAULT NULL
  
);